version: '3.1'

services:
  db:
    container_name: pg_database
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: car_rental

  car-rent:
    container_name: car-rent
    build:
      context: .
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: always